### ISSUE TITLE
fail on -iL option

### ISSUE THREAD

**Issue by localblackhat** [deepsecurity-pe/GoGhost#1]
~/scanner# ./GoGhost_linux_amd64 -iL /root/scanner/xaz > vulnips.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e28dc]

goroutine 1 [running]:
main.Hosts(0xc0000a6020, 0x11, 0xc000040ec0, 0x1, 0x1, 0x37, 0x0)
        /root/Desktop/smbgost/fixed.go:148 +0x7c
main.main()
        /root/Desktop/smbgost/fixed.go:215 +0xc57

cat xaz | wc -l
500

head xaz
xxxxx.xxxxx/29 
xx.xxxx.xxx/29 
xxxxxxx.xxx/29 
xx.xxxx.xx/29 
xx.xxxx.xx/29

**Comment by Dedal0** [comment]
Hi, seems and error on parsing the CIDR, to get a make a better troubleshoot pls share some of the IP ranges ur trying to scan or use the -iR option to see in what IP is the problem.

Hola, parece que el error es al momento del parsear el CIDR, para poder resolver el problema por favor compárteme que rango estás probando o tu mismo puedes usar la opicón -iR y escanear rango por rango y ver en cual está fallando.
